---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fourdaily
  namespace: velero
spec:
  schedule: 5 */6 * * *
  skipImmediately: false
  template:
    csiSnapshotTimeout: 0s
    hooks: {}
    includedNamespaces:
      - '*'
    itemOperationTimeout: 0s
    metadata: {}
    ttl: 360h0m0s
  useOwnerReferencesInBackup: false
