apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-read-all-servicemonitors-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-read-all-servicemonitors
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
