---
apiVersion: v1
kind: Service
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    app: external-pihole
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-pihole
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.0.2
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    app: external-pihole
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 3s
      path: /metrics
  selector:
    matchLabels:
      app: external-pihole
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: external-yoga
  namespace: monitoring
  labels:
    app: external-yoga
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-yoga
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.0.10
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-yoga
  namespace: monitoring
  labels:
    app: external-yoga
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 3s
      path: /metrics
  selector:
    matchLabels:
      app: external-yoga
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: external-odin
  namespace: monitoring
  labels:
    app: external-odin
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-odin
  namespace: monitoring
subsets:
  - addresses:
    - ip: 35.177.81.185
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-odin
  namespace: monitoring
  labels:
    app: external-odin
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 3s
      path: /metrics
  selector:
    matchLabels:
      app: external-odin
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: external-freya
  namespace: monitoring
  labels:
    app: external-freya
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-freya
  namespace: monitoring
subsets:
  - addresses:
    - ip: 3.8.9.103
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-freya
  namespace: monitoring
  labels:
    app: external-freya
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 3s
      path: /metrics
  selector:
    matchLabels:
      app: external-freya
  namespaceSelector:
    matchNames:
      - monitoring



---
apiVersion: v1
kind: Service
metadata:
  name: remote-node-exporter
  namespace: monitoring
  labels:
    app: remote-node-exporter
spec:
  clusterIP: None  # Headless service to enable custom EndpointSlices
  ports:
    - port: 9100
      name: metrics


