---
apiVersion: v1
kind: Service
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    app: external-pihole
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    kubernetes.io/service-name: external-pihole
addressType: IPv4
ports:
  - name: metrics
    port: 9100
endpoints:
  - addresses:
      - 192.168.0.2
  - conditions:
      - ready: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    app: external-pihole
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: external-pihole
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: external-yoga
  namespace: monitoring
  labels:
    app: external-yoga
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-yoga
  namespace: monitoring
  labels:
    kubernetes.io/service-name: external-yoga
addressType: IPv4
ports:
  - name: metrics
    port: 9100
endpoints:
  - addresses:
      - 192.168.0.10
  - conditions:
      - ready: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-yoga
  namespace: monitoring
  labels:
    app: external-yoga
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: external-yoga
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: external-odin
  namespace: monitoring
  labels:
    app: external-odin
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-odin
  namespace: monitoring
  labels:
    kubernetes.io/service-name: external-odin
addressType: IPv4
ports:
  - name: metrics
    port: 9100
endpoints:
  - addresses:
      - 35.177.81.185
  - conditions:
      - ready: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-odin
  namespace: monitoring
  labels:
    app: external-odin
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: external-odin
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: external-freya
  namespace: monitoring
  labels:
    app: external-freya
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-freya
  namespace: monitoring
  labels:
    kubernetes.io/service-name: external-freya
addressType: IPv4
ports:
  - name: metrics
    port: 9100
endpoints:
  - addresses:
      - 3.8.9.103
  - conditions:
      - ready: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-freya
  namespace: monitoring
  labels:
    app: external-freya
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  selector:
    matchLabels:
      app: external-freya
  namespaceSelector:
    matchNames:
      - monitoring

