---
apiVersion: v1
kind: Service
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    app: external-pihole
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-pihole
  namespace: monitoring
subsets:
  - addresses:
    - ip: 192.168.0.2
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-pihole
  namespace: monitoring
  labels:
    app: external-pihole
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 3s
      path: /metrics
  selector:
    matchLabels:
      app: external-pihole
  namespaceSelector:
    matchNames:
      - monitoring
