---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret-access-key
  namespace: cert-manager
spec:
  encryptedData:
    secretAccessKey: AgADZmdtAsxDQN8P0vBfKKNyPLWHj5Lohr5jDg4e/UWUfZx9uadyD/RP2CdaJlw9W5wXszT4Zzlc4+mFIlB1i83/QmfrCZSz2u7tJcf2ooxnuDEeZvsP1qCAe2uN46zrrE7lgi47lzpL8POFr2eWNpX4LuzBxbIYoxDoO6ulxg5KOLBmfwSih15Nmbngvpp7E8GvkYdlSKbxvz8hptnNwKeoVceZ1MLHljDgr+n1OHyOmWS0pRONiirEX9KmDSQm9iGzUakTC0ziAJ0Ix/P19XWLbrLwOgt3q+14CO7eUpfBnH6oS311oYSfp6BNylWmrR+UNhbply7e2oIc9Szc31MKSNMhlaCfh/l2QXEw6IyTDScLzOmMGICYANMX4BfqYtHnsUAet/ctl/QICA5hhoZApVJsJ9nW8j6x3JvjqFIcV28VWWR5WHVYJum2aID2ktDVYxgqfjHWwNNqVI9gFLWCjApunIWu3VCifRtg5lODRmGObIfC8G3nQMIK8hjiFOemcUeyh9RQhYxKv/pkqwSqPsmk6Z7NzzEkGw3BUuBTciuH7N5OrSV/WIikXSxpRZ1ishkuxr/1GNDsXv84pH6/1J+TfsOjtavm70+L33wXTQZa0riDtrMleOcvZRSLsPoeWnSoIoW3wXibhBeGoQB/6yTjWFpL7LkE2Y+xEibFl+NkAkA1QOwT7zYHSkpQ5GTsYxHtNkAjn82mFvhKxTOdAr8kf/82+GZhXYDEGhEoTYIQ85MxzIDz
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret-access-key
      namespace: cert-manager
    type: Opaque
