---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    credentials: AgAWbIIL4bExsg5F/rARtG9igLHrQ65oTkj5el8TJQWPxC035a9XQNDlJWa2BtDu9gaExgEdJU20jzcajH1ENHA90yRMJadioY0s01p9MlY2Jx6SlzRhK5tWdRgajewA4RnWgUrtnDC84D821pz5xyVtUTCcqW4eYT9MRhaoLfYM26/BP6H6nf94Qn7evr+/CsBZ8yvd1XhTcpWvyvDHyJkn9T/Do/4th49VXQUH2HMvfKb6FyMq0MhB2R33VsaG57U49ghuZBd+JGqnM2NA/U+arQA0Z0kYNWtpb8HguyK6ZhOVifqZMmKrQWAWcuEyLdC3r/YNSvqPRbnGdwvZJrkYH8mx51MV0Wkoe8Rh93ZuPrJ0JInicVphT/IxdwhZEem10MjUG/k5QpREseDpgBwzR/tMsjtdTRlau5tct8w1T+1Ns+zLJBJMBwMNyR3mtXyZCy+l5UEIq2pNMMFyZ16y8Oskeb94OPy5hoOTkeEZcQkNecM2L/Gd3YyteX106Ybm+BVBBiLb/jmNTkbruwmg3yunlKdyErLPBbR/bRgFjTQc+0iPvJm6Lf4vSSEYqG/ukerwb/S6Q9UfcMqc16+DDlGdJxlW6NYOPjmYVPFKDHqEaSGDITGwUzAZAuRjULzx3EK0IScQfOGC0DxGRMbTJyKHceNPcP6Nyl7wdqTq9LMMgj7PBHu8gUGf1yYlpgGRPCxi3WBUM3oemGWvL1aTrOZLpRj1Nf/MnJcsMCKn9YjKvzpIaz7/+An/aDWIUjs9lKgyt0iZyMyHplC9ordFASQmZN1wO3VAnHkTDbD9Xt/Q0I6nDC8j1yWbZSs4XAgWowAp8f+IjjjKaoseoJzI4x2smc4=
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
    type: Opaque
