---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-env-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgAZdDiMbLS9gBCK2IjOs3foLk6SD/OUO+MkPPehhPulrqoVQJzhXpqsUXnwBft+UqE+XgHD3u8sYfphDTCMn4CywT0Vre0Zpx8loYf708wnBl1yh3zOnmku4qqK5979T+mpPXPsP1ZI1lWM1ArdoXWkPZknXhOH6dbg2BdTZ3cGVDDoI0VQt0PNOnDk7kkJ81/TXBnxVGwKpRvCV/ytRekshPl41C7n24M3Xwe8R9nD3IoF23QTJCy6HZwbEk8EToF1Bab/GpaYBRXXBiYTn6TtVGiKZTEeJGvvNofWX1WpjeUiuxNwWBdI+QcOunJeO4TjxFV+5n85PiiR8NUkjcyTq0r9pKpEw1vwyVfS14pz/wYS/DBIiWNvIs+h76c3Df0Smu6XE1NMJNVPtwtLrNaZx/74JjRhIOXQTmTtpnfJobuMoS7FEbzRwHDSc7ls/dXu7LAHLJWb7nQta8W0nfAsx2PsgRaWKeiXtGFwith1DVxL44QJVW56H3+I+wsOFlF/pTpz9SnrsG19D19x5xeq3uyZFTP3BqbMMPGBMKupTj4oz0MXANlmnedzEbtMaArNcsvw6GRw6sW9uDBKWQ02xlUbKOhWv87JxE/M/DotJ8tBpqKeh+pj2gM5AW1K7LmSfuRDeAoP8GBUDxqavpL48s+ioA1682bkhx7Z5OEaVr0xLAdK3t+Ga5XBG4gsKGc8aUuyNjMQ
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCFb9UdH7Elyuc+TPWm9uIAFYC9M182jfG5Lw/3jBDVjyHTqotyRKLydGVAVsguj6J+UYXl0/2H4eoj3IliBYNeNLBIJLZMiyg9r+R9wg3OYKpklEo4xfH1+WYZUVwQYEjYvt7jR3esxPuCKQQ0Db6h4hrmrOxdXogjNhXe67o4HjdVO6c5F5xi831mBfDcGrL/0hG39sNc0byaos0JetPuhP10DiZ7JTriHDpFYvHNYRlPZXjUYfN6m7qjsLgQhoa0rOdbdosEsupYw1aBPkkvP4/pX37uG6DKUkfpc7g+2IqspnIu+nFcXK2f3nPHA06JLZBUSRHYTWU6XF8NuHUwcbSwMTP8mfY+Tl/VtK5uHS52jZ4QAuswuzlWqh0UZBus98hovqA0omEvz6R6W3xpmXpVkxN9KFpK0jeSSJ6bUjjmQAi/+Pd+abhGWOPImXpkr+pSx4WuEMq8egdvwBRV7VWrw1aCdn57hP/q7HtVv2L2CQiey1QRcD5sFMDNEgnGmemCRrT04e37W3CmmwDM8lpAeGlobtrtxZq6Yh8tgwCsfGRh/3272sw+apILCTRKLiXstc/TguzZ+vPGrytelUSmYu3ao5IbeRocAgOvn/FT1Pxfi+moopQIxK56qm02iXYpjXyRzH8Ltifl4tEztIaVNLXJTFcxbp5NfKehMuXkCkPDXbCISRTlk5QMjhLpdAgf80maHCdgRMGDBEFiGK4VN+FwZl0apPExsqM2tQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-env-secret
      namespace: monitoring
