apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bocan/argocd-lab.git
    path: charts/descheduler
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
