apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bocan/argocd-lab.git
    path: charts/keycloak
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
