apiVersion: v2
name: external-dns
version: 1.0.0
dependencies:
  - name: external-dns
    version: 1.15.0
    repository: https://artifacthub.io/packages/helm/external-dns
    namespace: external-dns
