external-dns:
  provider:
    name: aws
  #extraVolumes:
  #  - name: aws-credentials
  #    secret:
  #      secretname: external-dns
  #extraVolumeMounts:
  #  volumeMounts:
  #    - name: aws-credentials
  #      mountPath: /.aws
  #      readOnly: true
  domainFilters: ["funderburg.uk"]
  env:
    - name: AWS_DEFAULT_REGION
      value: eu-west-1
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /.aws/credentials
