external-dns:
  provider:
    name: aws
  extraVolumes:
    - name: aws-credentials
      secret:
        secretName: external-dns
  extraVolumeMounts:
    - name: aws-credentials
      mountPath: /.aws
      readOnly: true
  domainFilters: ["funderburg.uk"]
  sources:
    - ingress
  managedRecordTypes:
    - A
  env:
    - name: AWS_DEFAULT_REGION
      value: eu-west-2
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /.aws/credentials
  logLevel: debug
