keycloak:

  postgresql:
    auth:
      postgresPassword: "password"
      password: "password"

  ingress:
    enabled: true
    ingressClassName: "traefik"
    hostname: keycloak.funderburg.uk
    servicePort: http
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/host: "keycloak.funderburg.uk"

    tls: true

    extraTls:
    - hosts:
        - keycloak.funderburg.uk
      secretName: keycloak.local-tls

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      namespace: "monitoring"
      labels: {}
      groups:
        - name: Keycloak
          rules:
            - alert: KeycloakInstanceNotAvailable
              annotations:
                message: "Keycloak instance in namespace {{ `{{` }} $labels.namespace {{ `}}` }} has not been available for the last 5 minutes."
              expr: |
                absent(kube_pod_status_ready{namespace="{{ include "common.names.namespace" . }}", condition="true"} * on (pod) kube_pod_labels{pod=~"{{ include "common.names.fullname" . }}-\\d+", namespace="{{ include "common.names.namespace" . }}"}) != 0
              for: 5m
              labels:
                severity: critical

  adminIngress:
    enabled: true
    ingressClassName: "traefik"
    hostname: keycloak.funderburg.uk
    servicePort: http
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/host: "keycloak.funderburg.uk"

    tls: true

    extraTls:
    - hosts:
        - keycloak.funderburg.uk
      secretName: keycloak.local-tls
