apiVersion: v2
name: kube-prometheus-stack
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 67.3.1
    repository: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
