apiVersion: v1
kind: Secret
metadata:
  name: grafana-env-secret
  namespace: monitoring
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: SEZhTjQwcHQzTlkzV3o0dkZmNGp2RHF0MGkzUkpGd3o=
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: Z3JhZmFuYQ==

