kube-prometheus-stack:
  ## Create default rules for monitoring the cluster
  ##
  defaultRules:
    create: true
    rules:
      etcd: false

  kubeApiServer:
    enabled: true
    tlsConfig:
      insecureSkipVerify: true

  kubelet:
    insecureSkipVerify: true

  alertmanager:
    ingress:
      enabled: true
      ingressClassName: traefik

      #annotations:
      #  external-dns.alpha.kubernetes.io/host: "alertmanager.funderburg.uk"
      #  cert-manager.io/cluster-issuer: letsencrypt-prod

      hosts:
      - alertmanager.funderburg.uk

      ## Paths to use for ingress rules - one path should match the alertmanagerSpec.routePrefix
      ##
      paths:
      - /

      ## TLS configuration for Alertmanager Ingress
      ## Secret must be manually created in the namespace
      ##
      tls:
      - secretName: alertmanager-general-tls
        hosts:
        - alertmanager.funderburg.uk

  grafana:

    adminPassword: prom-operator

    ingress:
      enabled: true

      ingressClassName: traefik

      annotations:
        external-dns.alpha.kubernetes.io/host: "grafana.funderburg.uk"
        cert-manager.io/cluster-issuer: letsencrypt-prod

      ## Hostnames.
      ## Must be provided if Ingress is enable.
      ##
      hosts:
      - grafana.funderburg.uk

      tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.funderburg.uk

    persistence:
      enabled: true
      type: sts
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection

  kubeControllerManager:
    endpoints: ['192.168.0.51']
    insecureSkipVerify: true

  kubeEtcd:
    enabled: false

  kubeScheduler:
    endpoints: ['192.168.0.51']
    insecureSkipVerify: true

  kubeProxy:
    enabled: true

    endpoints: ['192.168.0.51']
    insecureSkipVerify: true

  prometheus:
    enabled: true

    ingress:
      enabled: true

      ingressClassName: traefik

      annotations:
        external-dns.alpha.kubernetes.io/host: "prometheus.funderburg.uk"
        cert-manager.io/cluster-issuer: letsencrypt-prod

      hosts:
        - prometheus.funderburg.uk

      paths:
      - /

      tls:
      - secretName: prometheus-general-tls
        hosts:
          - prometheus.funderburg.uk

    ## Settings affecting prometheusSpec
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
    ##
    prometheusSpec:
      ## Statefulset's persistent volume claim retention policy
      ## pvcDeleteOnStsDelete and pvcDeleteOnStsScale determine whether
      ## statefulset's PVCs are deleted (true) or retained (false) on scaling down
      ## and deleting statefulset, respectively. Requires 1.27.0+.
      ## Ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention
      persistentVolumeClaimRetentionPolicy:
        whenDeleted: Retain
        whenScaled: Retain

      ## How long to retain metrics
      ##
      retention: 10d
      ##
      retentionSize: ""

      ## Prometheus StorageSpec for persistent data
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      ##
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
