argo-cd:
  global:
    domain: argocd.example.com
  server:
    # Argo CD server ingress configuration
    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: true
      # -- Additional ingress annotations
      ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
      annotations:
        external-dns.alpha.kubernetes.io/host: "argocd.funderburg.uk"
      # -- Defines which ingress controller will implement the resource
      ingressClassName: traefik
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false







