argo-cd:
  global:
    domain: argocd.funderburg.uk
  configs:
    params:
      server.insecure: true
  server:
    # Argo CD server ingress configuration
    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: true
      # -- Additional ingress annotations
      ## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
      annotations:
        external-dns.alpha.kubernetes.io/host: "argocd.funderburg.uk"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      # -- Defines which ingress controller will implement the resource
      ingressClassName: traefik
      tls: true

      extraTls:
        - hosts:
          - argocd.funderburg.uk
          secretName: argocd-funderburg-uk-tls
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

  repoServer:
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

  controller:
    resources:
      limits:
        cpu: 500m
        memory: 640Mi
      requests:
        cpu: 250m
        memory: 384Mi
  redis:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
