grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    path: /

    # pathType is only for k8s >= 1.1=
    pathType: Prefix

    hosts:
      - grafana.local
  persistence:
    type: pvc
    enabled: true
