apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: chris@funderburg.me
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              name: aws-access-key-id
              key: accessKeyId
            secretAccessKeySecretRef:
              name: aws-secret-access-key
              key: secretAccessKey
            region: eu-west-2
